const DataTable = () => {
    return (
        <div className="table-responsive">
            <table className="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Data</th>
                        <th>Vendedor</th>
                        <th>Clientes visitados</th>
                        <th>Negócios fechados</th>
                        <th>Valor</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Adriana</td>
                        <td>34</td>
                        <td>25</td>
                        <td>15017.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Mari</td>
                        <td>34</td>
                        <td>25</td>
                        <td>12517.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Wellington</td>
                        <td>34</td>
                        <td>25</td>
                        <td>11817.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Yaskara</td>
                        <td>34</td>
                        <td>25</td>
                        <td>10017.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Kedma</td>
                        <td>34</td>
                        <td>25</td>
                        <td>9217.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Michele</td>
                        <td>34</td>
                        <td>25</td>
                        <td>10017.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Karina</td>
                        <td>34</td>
                        <td>25</td>
                        <td>9877.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Marcos</td>
                        <td>34</td>
                        <td>25</td>
                        <td>8417.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Vinicius</td>
                        <td>34</td>
                        <td>25</td>
                        <td>7317.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Marcia</td>
                        <td>34</td>
                        <td>25</td>
                        <td>6787.00</td>
                    </tr>
                    <tr>
                        <td>22/04/2021</td>
                        <td>Celeste</td>
                        <td>34</td>
                        <td>25</td>
                        <td>5047.00</td>
                    </tr>
                </tbody>
            </table>
        </div>
    );
}

export default DataTable;